### ISSUE TITLE
Microphone issues

### ISSUE THREAD

**Issue by rurulol** [gordonbay/Windows-On-Reins#13]
kinda screwed over my microphone, checked all drivers etc, usually fixed issues like this by troubleshooting but now i cant troubleshoot... any ideas?

**Comment by rurulol** [comment]
Oh and I forgot.. My USB microphone works but the mic from my headphones which goes into the rear mic input doesn't

**Comment by gordonbay** [comment]
Have you tested the $beMicrophoneSafe option?

**Comment by rurulol** [comment]
just did it, works, thank you
