### ISSUE TITLE
Downloading MSStore applications doesnt work after running script

### ISSUE THREAD

**Issue by Blu3ish** [gordonbay/Windows-On-Reins#15]
So... where to start I wish this script delivered the results without negatives because it really looks to be working wonders.

Unfortunately you're not able to install any applications from the windows store after running this script.

$beXboxSafe
$disableMSStore
are set to 0

I tried to comment out these deinstallations without any results I thought they might cause the problem:
Microsoft.Appconnector
Microsoft.StorePurchaseApp

![image](https://user-images.githubusercontent.com/36703662/174045001-4a0e4937-d2a5-41fa-8644-4e37b79125b7.png)

No results yet. I hope anyone could help to make the function $disableMSStore actually work.

**Comment by gordonbay** [comment]
$beAppxSafe = 1 may fix it

**Comment by HoodedMenace9** [comment]
Yeah Id like to be able to use my Microsoft store and apps.. how do enable them again?
