### ISSUE TITLE
Time Broker Cause Problem with Task Scheduler when disabled 

### ISSUE THREAD

**Issue by dennyamarojr** [gordonbay/Windows-On-Reins#2]
Hi gordon,

I was testing disabling Time Broker in Windows 10 20H2 and breaks task scheduler service avoiding tasks being loaded in the system.

**Comment by gordonbay** [comment]
Hi, i created the beTaskScheduleSafe option to track the scheduler dependencies.

**Comment by dennyamarojr** [comment]
That's good, will test the new version

**Comment by dennyamarojr** [comment]
Sorry to take too long to reply, test the new version and it seems that Time broker still being disabled (I had to manually re-enable).

**Comment by gordonbay** [comment]
beTaskScheduleSafe  working perfectly on w11
