### ISSUE TITLE
Explorer not working

### ISSUE THREAD

**Issue by TheKidRock** [gordonbay/Windows-On-Reins#21]
I run this script on my Windows 11 Pro laptop and processes were reduced from 165 to 125.... that was impressive.

However, I could not open any Drives, Folders. Tried to run System Restore and that was not working too. Then tried to run System Image Backup from Recovery, but that option was not also available in Recovery Advanced Options. Tried few hours to solve the issues but in vain. So, finally, had to reinstall Windows 11 from USB again.

Want to run this script again, but I fear Explorer may not work again, and I won't be able to open any drives and folders. Since, I am not a very technical person, is there a GUI version so that it will be easier to select only what I need to disable/uninstall? Or any other way to SAFELY run the script with my limited knowledge?

**Comment by oisgrafika** [comment]
same gere dude

**Comment by oisgrafika** [comment]
but i fix it with enable all services that this script deactivates

**Comment by TheKidRock** [comment]
> but i fix it with enable all services that this script deactivates

If you enable all services, then it will be like default Windows 11 settings without any optimizations. There must be a tweak to make this script work. Hope @gordonbay provides a solution/update.

**Comment by QuiteAFancyEmerald** [comment]
Same issue as well.

**Comment by gordonbay** [comment]
Im doing some tests, still not able to find the roots cases to the explorer crash

**Comment by gordonbay** [comment]
Fixed

**Comment by TheKidRock** [comment]
Thanks. I have updated Windows 11 to the latest 23H2 version. File explorer is working fine now. 

I have changed a few configurations in "wor.ps1" file as below.

> $troubleshootInstalls = 1
$beAppxSafe = 1
$beCastSafe = 1
$beVpnPppoeSafe = 1
$beTaskScheduleSafe = 1
$useGoogleDNS = 0
$installNvidiaControlPanel = 0
$darkTheme = 0
$draculaThemeNotepad = 0
$disableWindowsFirewall = 0
$disableWindowsUpdates = 0
$disableSystemRestore = 0
$disableNtfsEncryption = 0
$disableVBS = 0
$firefoxSettings = 0
$disableWindowsSounds = 0
$unpinStartMenu = 0
$unnistallWindowsDefender = 0

I have enabled Windows Update, but update does not work and displays error. Do I need to edit anything else for Windows Update to work?
