### ISSUE TITLE
Peronalization - Themes : "System detected an overrun of a stack-based buffer in this application"

### ISSUE THREAD

**Issue by maykimas** [gordonbay/Windows-On-Reins#3]

**Comment by gordonbay** [comment]
Hi, need more info about this.

**Comment by maykimas** [comment]
Event viewer

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Popup" Guid="{47bfa2b7-bd54-4fac-b70b-29021084ca8f}" /> 
  <EventID>26</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2021-02-02T18:29:27.599513500Z" /> 
  <EventRecordID>56749</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="888" ThreadID="1268" /> 
  <Channel>System</Channel> 
  <Computer>MyComputer</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="Caption">SystemSettings.exe - System error</Data> 
  <Data Name="Message">The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.</Data> 
  </EventData>
  </Event>

**Comment by gordonbay** [comment]
What windows version?

**Comment by maykimas** [comment]
Windows 10 Home 64 bits 1909 - 18363.1316 -

**Comment by gordonbay** [comment]
All testing is done on PRO version.
